### ISSUE TITLE
use with the chrome often returns 400 errors

### ISSUE THREAD

**Issue by dpcrman** [stulzq/IdentityServer4.Samples#1]
![image](https://user-images.githubusercontent.com/7519765/43713316-c7163856-99ab-11e8-87f9-830ded4b122d.png)

![image](https://user-images.githubusercontent.com/7519765/43713323-ca082ede-99ab-11e8-9dc4-947a3cea07df.png)

**Comment by stulzq** [comment]
Why do you create two identical issues?
