### ISSUE TITLE
use with the chrome often returns 400 errors

### ISSUE THREAD

**Issue by dpcrman** [stulzq/IdentityServer4.Samples#2]
![image](https://user-images.githubusercontent.com/7519765/43713316-c7163856-99ab-11e8-87f9-830ded4b122d.png)

![image](https://user-images.githubusercontent.com/7519765/43713323-ca082ede-99ab-11e8-9dc4-947a3cea07df.png)

![image](https://user-images.githubusercontent.com/7519765/43713498-679e3882-99ac-11e8-9f6f-c79d3dcb6629.png)

**Comment by stulzq** [comment]
This repository just provides sample code, and then solves the problem that occurs with the demo, does not solve other problems, thank you.
